#!/usr/bin/env sh

STAGED_PHP=$(git -c core.quotepath=false diff --cached --name-only --diff-filter=ACMR -- '*.php')

if [ -n "$STAGED_PHP" ]; then
  echo "Formatage du code (Pint)…"
  ./vendor/bin/pint --dirty
  git add $STAGED_PHP
fi
